name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install workspace dependencies
      run: |
        npm run install:extension
        npm run install:frontend
        npm run install:backend
      
    - name: Lint React Frontend
      run: npm run lint --workspace=react-frontend
      
    - name: Type check React Frontend
      run: npm run type-check --workspace=react-frontend
      
    - name: Build React Frontend
      run: npm run build --workspace=react-frontend
      
  build-extension:
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install workspace dependencies
      run: npm run install:extension
      
    - name: Build Chrome Extension
      run: npm run build:prod --workspace=chrome-extension
      
    - name: Upload Extension Build
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension-build
        path: chrome-extension/dist/
