name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, staging]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ","
          files_ignore: |
            **/*.lock
            **/*.log
            **/node_modules/**
            **/dist/**
            **/build/**

      - name: Review changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: anthropics/claude-github-action@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          claude-model: "claude-3-5-sonnet-20241022"
          changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
          review-prompt: |
            Review only the changed files in this PR. Focus on:

            **Security (High Priority):**
            • No API keys, tokens, or credentials committed
            • Proper input validation and sanitization
            • Authentication and authorization implementation
            • SQL injection and XSS prevention
            • Secure data handling and storage

            **Code Quality:**
            • Logic errors and potential bugs
            • Performance implications
            • Error handling
            • Type safety (TypeScript)

            **Best Practices:**
            • Framework-specific patterns (React, Express, etc.)
            • Database schema changes and migrations
            • API design and data structures

            Keep comments concise and actionable. Only flag genuine issues.
