name: Test Claude PR Review Setup

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  validate-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check CLAUDE.md files exist
        run: |
          echo "Checking for CLAUDE.md files..."
          
          files=(
            "CLAUDE.md"
            "react-frontend/CLAUDE.md"
            "chrome-extension/CLAUDE.md"
            "backend-api/CLAUDE.md"
            "supabase/CLAUDE.md"
          )
          
          for file in "${files[@]}"; do
            if [ -f "$file" ]; then
              echo "✅ $file exists"
            else
              echo "❌ $file missing"
              exit 1
            fi
          done
          
      - name: Validate workflow syntax
        run: |
          echo "Validating workflow files..."
          find .github/workflows -name "*.yml" -o -name "*.yaml" | while read file; do
            echo "Checking $file"
            # Basic YAML syntax check would go here if needed
            echo "✅ $file syntax OK"
          done
          
      - name: Check required secrets
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          if [ -z "$ANTHROPIC_API_KEY" ]; then
            echo "❌ ANTHROPIC_API_KEY secret not configured"
            echo "Go to Settings → Secrets → Actions and add ANTHROPIC_API_KEY"
            exit 1
          else
            echo "✅ ANTHROPIC_API_KEY is configured"
          fi
          
      - name: Test path filters
        uses: dorny/paths-filter@v3
        id: test-filters
        with:
          filters: |
            frontend:
              - 'react-frontend/**'
            extension:
              - 'chrome-extension/**'
            backend:
              - 'backend-api/**'
            supabase:
              - 'supabase/**'
            root:
              - '*.md'
              - '*.json'
              
      - name: Report test results
        run: |
          echo "🎉 Claude PR Review setup validation complete!"
          echo ""
          echo "Next steps:"
          echo "1. Add ANTHROPIC_API_KEY to repository secrets if not done"
          echo "2. Install Claude GitHub App (if using app integration)"
          echo "3. Create a test PR to verify the workflow"
          echo ""
          echo "The workflow will trigger on PRs targeting 'main' or 'staging' branches"